window.__AUTH_CONFIG__ = {
  localHosts: ['localhost', '127.0.0.1'],
  trustedAppOrigins: [
    'https://blueprint.continental-hub.com',
    'https://dashboard.continental-hub.com',
    'https://grimoire.continental-hub.com',
    'https://login.continental-hub.com',
    'https://pulse.continental-hub.com',
    'https://stepcast.continental-hub.com',
    'https://vanguard.continental-hub.com',
    'https://charlemagne404.github.io',
    'https://mpmc.ddns.net',
  ],
  trustedApiOrigins: [
    'https://dashboard.continental-hub.com',
    'https://grimoire.continental-hub.com',
    'https://login.continental-hub.com',
    'https://continental-hub.com',
    'https://api.continental-hub.com',
    'https://auth.continental-hub.com',
    'https://id.continental-hub.com',
    'https://backend.continental-hub.com',
    'https://mpmc.ddns.net',
  ],
  preferredApiOrigins: [
    'https://api.continental-hub.com',
    'https://auth.continental-hub.com',
    'https://id.continental-hub.com',
    'https://backend.continental-hub.com',
    'https://continental-hub.com',
    'https://login.continental-hub.com',
  ],
  defaultDashboardOrigin: 'https://dashboard.continental-hub.com',
  hostedApiBaseUrl: 'https://auth.continental-hub.com',
  authApps: {
    grimoire: {
      appId: 'grimoire',
      displayName: 'Grimoire',
      allowedOrigins: ['https://grimoire.continental-hub.com'],
      allowedRedirectOrigins: ['https://grimoire.continental-hub.com'],
      firstParty: true,
    },
    blueprint: {
      appId: 'blueprint',
      displayName: 'Blueprint',
      allowedOrigins: ['https://blueprint.continental-hub.com'],
      allowedRedirectOrigins: ['https://blueprint.continental-hub.com'],
      firstParty: true,
    },
    vanguard: {
      appId: 'vanguard',
      displayName: 'Vanguard',
      allowedOrigins: ['https://vanguard.continental-hub.com'],
      allowedRedirectOrigins: ['https://vanguard.continental-hub.com'],
      firstParty: true,
    },
  },
};
